#!/usr/bin/env sh

echo "Contents:"
echo "==========="
echo

echo ".. toctree::"
echo
echo "   README.md"

find . -maxdepth 1 -type d ! -path "." ! -path "./.git" ! -path "./draft" | sort | cut -c 3- | while read DIR; do
	echo
	echo ".. toctree::"
	echo "   :caption: ${DIR}"
	echo
	ls "${DIR}" | sed "s/^/   ${DIR}\\//"
done
#for cata in `echo "${catas}"`; do
#	lists=`find "${cata}" -maxdepth 1 -type f -regex ".+\.md" | sort`
#	if [ -n "${lists}" ]; then
#		title="${cata:2}"
#		title="${title//_/ }"
#		echo ".. toctree::" >> index.rst
#		echo "   :caption: ${title}" >> index.rst
#		echo >> index.rst
#		for mdfile in `echo "${lists}"`; do
#			echo "   ${mdfile:2}" >> index.rst
#		done
#		echo >> index.rst
#	fi
#done
#
#git add index.rst
#
#cat index.rst

