#!/usr/bin/env sh

echo "Contents:"
echo "==========="
echo

echo ".. toctree::"
echo
echo "   README.md"

find . -maxdepth 1 -type d ! -path "." | cut -c 3- | grep '^[0-9]_' | sort | while read DIR; do
	echo
	echo ".. toctree::"
	echo "   :caption: ${DIR:2}"
	echo
	ls "${DIR}" | sort | sed "s/^/   ${DIR}\\//"
done
